const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const outletSchema = new Schema({
    resname: { type: String, required: true, },
    pan: { type: String, required: true, },
    gst: { type: Number, required: true, },
    fssai: { type: Number, required: true, },
    restype:[{type:String, required: true}] ,
    tablebooking:{type: String, required: true},
    partnerdelivery:{type: String, required: true},
    outletstatus:{type: String, required: true},
    onlinedelivery:{type: String, required: true},
    currencytype:{type: String, required: true},
    cuisines:[{type:String, required: true}] ,
    starttime:{type:String, required: true},
    endtime:{type:String, required: true},
    city: { type: String, required: true, },
    pincode: { type: Number, required: true, },
    address: { type: String, required: true, },
    locality: { type: String, required: true, },
    zone: { type: String, required: true, },
    state: { type: String, required: true, },
    city: { type: String, required: true, },
    latitude: { type: Number, required: true, },
    longitude: { type: Number, required: true, },
    con1: { type: Number, required: true, },
    con2: { type: Number, required: true, },
    con3: { type: Number, required: true, },
    landline: { type: Number, required: true, },
    mail: { type: String, required: true, },
    weblink: { type: String, required: true, },
    avgcost: { type: Number, required: true, },
    fname: { type: String, required: true, },
    lname: { type: String, required: true, },
    phone: { type: Number, required: true, },
    email: { type: String, required: true, },
    password: { type: String, required: true, },
},
    { timestamps: true,
});
const Outlet = mongoose.model('Outlet', outletSchema);
module.exports = Outlet;