import React, { useState } from "react";
import {
  Input,
  Grid,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  Button,
  IconButton,
  withStyles,
  makeStyles,
  Modal,
  Backdrop,
  Fade,
  Box,
  Typography,
  TextField
} from "@material-ui/core";
import DeleteIcon from "@material-ui/icons/Delete";
import EditIcon from "@material-ui/icons/Edit";

const useStyles = makeStyles((theme) => ({
  modal: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: 500,
    borderRadius: 10,
    boxShadow: 24,
    padding: 20,
    backgroundColor: theme.palette.mode === "light" ? "#fff" : "#212B36"
  }
}));

const createData = (sl, empName, empId, genDate, startDate, endDate, genBy) => {
  return {
    sl,
    empName,
    empId,
    genDate,
    startDate,
    endDate,
    genBy
  };
};

const data = [
  createData(
    1,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    2,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    3,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    4,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    5,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    6,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    7,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    8,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    9,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    10,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  ),
  createData(
    11,
    "Fayaz Saraj",
    "EHRZMEOC",
    "2021-10-20",
    "2021-12-10",
    "2021-12-31",
    "Admin"
  )
];

const SalaryGenerate = (props) => {
  const[rows, setRows] = useState(data);
  const [openModal, setOpenModal] = useState(false);
  const [openModal2, setOpenModal2] = useState(false);
  const [currIndex, setCurrIndex] = useState(null);

  const [empName, setempName] = useState("")
  const [startDate, setstartDate] = useState("")
  const [endDate, setendDate] = useState("")

  const classes = useStyles()

  const openModalHandler = () => {
    setOpenModal(true);
  };

  const closeModalHandler = () => {
    setOpenModal(false);
  };

  const openModalHandler2 = () => {
    setOpenModal2(true);
  };

  const closeModalHandler2 = () => {
    setOpenModal2(false);
  };

  const addPosition = () =>{
    let today = new Date(Date.now()).toLocaleString().split(',')[0]
    const index = rows.length;
    const newPosition = createData(index+1,empName, "ef4543",today, startDate, endDate, "admin")
    setRows(prev => [...prev,newPosition])
    setempName("")
    setstartDate("")
    setendDate("")

    closeModalHandler()
  }

  const deletePosition = (index) =>{
    if(window.confirm("Are you sure you want to delete this item?")){
      let newRows = rows.filter((row,i) =>{
        return index !== i;
      })
      setRows(newRows)
    }
  }

  const edit = (i) => {
    openModalHandler2()
    setCurrIndex(i)
    setempName(rows[i].empName)
    setstartDate(rows[i].startDate)
    setendDate(rows[i].endDate)

  }

  const editPosition = () =>{
    let newRows = rows.map(row => row);
    newRows[currIndex].empName = empName;
    newRows[currIndex].startDate = startDate;
    newRows[currIndex].endDate = endDate;

    setRows(newRows)
    setempName("")
    setstartDate("")
    setendDate("")
    closeModalHandler2()
  }

  const reset = () => {
    setempName("")
    setstartDate("")
    setendDate("")
  }

  const columns = [
    { label: "Sr. No.", minWidth: 40, maxWidth: 60 },
    { label: "Employee Name", minWidth: 100, maxWidth: 200 },
    { label: "Employee Id", minWidth: 100, maxWidth: 200 },
    { label: "Generate Date", minWidth: 100, maxWidth: 200 },
    { label: "Start Date", minWidth: 100, maxWidth: 200 },
    { label: "End Date", minWidth: 100, maxWidth: 200 },
    { label: "Generated By", minWidth: 100, maxWidth: 200 },
    { label: "Action", minWidth: 100, maxWidth: 200 }

  ];

  return (
    <>
      <Modal
          open={openModal}
          onClose={closeModalHandler}
          closeAfterTransition
          BackdropComponent={Backdrop}
        >
          <Fade in={openModal}>
            <Box className={classes.modal}>
              <Typography variant="h5" align="center">
                Generate Salary
              </Typography>
              <Grid item container direction="column" spacing={2} sx={{ padding: 2 }}>
                <Grid item container>
                  <Grid item xs={4}>
                    <Typography variant="subtitle2">Employee Name :</Typography>
                  </Grid>
                  <Grid item xs={8}>
                    <TextField fullWidth size="small"
                      value={empName}
                      onChange={e => setempName(e.target.value)} />
                  </Grid>
                </Grid>
                <Grid item container>
                  <Grid item xs={4}>
                    <Typography variant="subtitle2">From Date :</Typography>
                  </Grid>
                  <Grid item xs={8}>
                    <TextField type="date" fullWidth size="small"
                      value={startDate}
                      onChange={e => setstartDate(e.target.value)} />
                  </Grid>
                </Grid>
                <Grid item container>
                  <Grid item xs={4}>
                    <Typography variant="subtitle2">To Date :</Typography>
                  </Grid>
                  <Grid item xs={8}>
                    <TextField type="date" fullWidth size="small"
                      value={endDate}
                      onChange={e => setendDate(e.target.value)} />
                  </Grid>
                </Grid>


                <Grid item container justifyContent="flex-end">
                  <Grid item  >
                    <Button onClick={reset}  variant="outlined" size="small" sx={{ marginRight: 1 }}>
                      Reset
                    </Button>
                    <Button onClick={addPosition}  variant="contained" size="small">
                      Save
                    </Button>
                  </Grid>
                </Grid>
              </Grid>
            </Box>
          </Fade>
      </Modal>
      <Modal
          open={openModal2}
          onClose={closeModalHandler2}
          closeAfterTransition
          BackdropComponent={Backdrop}
        >
          <Fade in={openModal2}>
            <Box className={classes.modal}>
              <Typography variant="h5" align="center">
                Edit Generated Salary
              </Typography>
              <Grid item container direction="column" spacing={2} sx={{ padding: 2 }}>
                <Grid item container>
                  <Grid item xs={4}>
                    <Typography variant="subtitle2">Employee Name :</Typography>
                  </Grid>
                  <Grid item xs={8}>
                    <TextField fullWidth size="small"
                      value={empName}
                      onChange={e => setempName(e.target.value)} />
                  </Grid>
                </Grid>
                <Grid item container>
                  <Grid item xs={4}>
                    <Typography variant="subtitle2">From Date :</Typography>
                  </Grid>
                  <Grid item xs={8}>
                    <TextField type="date" fullWidth size="small"
                      value={startDate}
                      onChange={e => setstartDate(e.target.value)} />
                  </Grid>
                </Grid>
                <Grid item container>
                  <Grid item xs={4}>
                    <Typography variant="subtitle2">To Date :</Typography>
                  </Grid>
                  <Grid item xs={8}>
                    <TextField type="date" fullWidth size="small"
                      value={endDate}
                      onChange={e => setendDate(e.target.value)} />
                  </Grid>
                </Grid>


                <Grid item container justifyContent="flex-end">
                  <Grid item  >
                    <Button onClick={reset}  variant="outlined" size="small" sx={{ marginRight: 1 }}>
                      Reset
                    </Button>
                    <Button onClick={editPosition}  variant="contained" size="small">
                      Save
                    </Button>
                  </Grid>
                </Grid>
              </Grid>
            </Box>
          </Fade>
      </Modal>
      <Grid container spacing={2} justifyContent="right">
        <Grid item>
          <Button onClick={openModalHandler} variant="contained">Generate Now</Button>
        </Grid>
        <Grid item>
          <Button variant="outlined">Manage Salary Generate</Button>
        </Grid>
      </Grid>
      <Grid
        container
        style={{
          borderRadius: 5,
          border: "1px solid grey",
          boxSizing: "border-box",
          padding: "20px 20px",
          margin: "20px 0px"
        }}
        direction="column"
        rowGap={2}
      >
        <Grid item container style={{ padding: 0, justifyContent: "space-between" }}>
          <Grid item>
            <Button size="small">Copy</Button>
            <Button size="small">CSV</Button>
            <Button size="small">Excel</Button>
            <Button size="small">PDF</Button>
            <Button size="small">Print</Button>
          </Grid>
          <Grid item>
            <Input type="text" placeholder="Search" />
          </Grid>
        </Grid>

        <Table size="small" sx={{ minWidth: 1300 }}>
          <TableHead>
            <TableRow>
              {columns.map((column) => {
                return (
                  <TableCell
                    style={{ minWidth: column.minWidth, maxWidth: column.maxWidth }}
                    key={column.label}
                  >
                    {column.label}
                  </TableCell>
                );
              })}
            </TableRow>
          </TableHead>
          <TableBody>
            {rows.map((row,id) => {
              return (
                <TableRow key={row.sl} hover>
                  <TableCell>{row.sl}</TableCell>
                  <TableCell>{row.empName}</TableCell>
                  <TableCell>{row.empId}</TableCell>
                  <TableCell>{row.genDate}</TableCell>
                  <TableCell>{row.startDate}</TableCell>
                  <TableCell>{row.endDate}</TableCell>
                  <TableCell>{row.genBy}</TableCell>
                  <TableCell>
                          <IconButton onClick={()=>edit(id)} color="primary">
                            <EditIcon />
                          </IconButton>
                          <IconButton onClick={()=>deletePosition(id)} >
                            <DeleteIcon color="error"/>
                          </IconButton>
                    </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </Grid>
    </>
  );
};
export default SalaryGenerate;
